README.md
cht-instances.example.yml
prometheus/config/prometheus.yml
tests/fake-cht/index.js

Currently in the `cht-instances.yml` file, you have to configure your URL with the full path to the monitoring endpoint:
```yml
- https://gamma.dev.medicmobile.org/api/v2/monitoring?connected_user_interval=30
```
This is bad for two reasons:
1. Adds additional complexity to the manual configuration (easy to get wrong). And it has to be set for each repeated value.
2. Makes it difficult to re-use the `cht-instances.yml` file configurations for other types of scrapes.  In the future we probably will want to be able to scrape directly from Couch. In that case it would be nice to not have to duplicate this config somewhere else.
The ultimate goal is to just have a single place where administrators can configure the list of CHT instances to monitor.
While working  on scraping Postgres I …

feat: Update config so CHT urls do not need monitoring path

---

grafana/provisioning/dashboards/CHT/cht_admin_overview.json

This PR just changes the JSON to go from `CHT Admin Overview` to `CHT Watchdog`

feat (na) rebrand to Watchdog in admin overview

---

grafana/provisioning/alerting/cht.yml
grafana/provisioning/dashboards/CHT/cht_admin_overview.json

After auditing data across a number of instances it is clear that small  Couch DBs tend to have high fragmentation.  CouchDB compaction [only runs for DBs > 1mb](https://docs.couchdb.org/en/stable/config/compaction.html#smoosh.%7Bchannel-name%7D/min_size) (and we are not really concerned if small DBs are fragmented). So, I have updated this alert to only fire if the DB has `< 1000 docs`.  
There was a bug in this alert rule because it was loading data with multiple separate queries, but it could not join the data together when there is multiple CHT instances configured. So, it would work find when there was only one CHT instance, but would just stay in the "No Data" status when more than one CHT instance was being scraped.
I updated the alert rule to just use one big query that can join …

fix(35): update DB Fragmentation and Message Delivery Rate alerts

---

.gitignore
development/README.md
development/docker-compose.smtp.yml
development/fake-cht/docker-compose.fake-cht.yml
development/fake-cht/package-lock.json
development/fake-cht/package.json
docker-compose.yml
exporters/postgres/docker-compose.postgres-exporter.yml
grafana/provisioning/alerting/delete-rules.example.yml
package.json

- Adds `delete-rules.example.yml` file that can be copied and used to delete provisioned alert rules.
- Updates the Docker network name `cht-monitoring-net` to be `cht-watchdog-net`.
- Updates random references to CHT Monitoring to be "Watchdog".
- Fix repo link in package.json to point to https://github.com/medic/cht-watchdog.git
- Adds `name` property to fake-cht package.json file.  This should prevent the package-lock.json file getting updated when the fake-cht is built in the docker container.
Need to verify that everything still runs as expected and an in-place upgrade of an existing deployment goes smooth.
- Start by checking out the latest from `main`
- Run the [full test config](https://github.com/medic/cht-watchdog/tree/main/development#stream-random-data) for cht-watchdog
- Make …

feat(53): add recommended method for deleting provisioned alerts

---

grafana/provisioning/alerting/cht.yml

So, there was a bug in my fix for the DB Fragmentation alert in #37.  The query for the alert rule was not joining on the `instance` label when checking to be sure `cht_couchdb_doc_total > 1000`. It was only checking the `db` label.  But that meant that if _any of the instances_ being scraped by the Watchdog instance had a DB (e.g. a `_users` db) with more than 1000 docs, then the alert would still fire for that `_users` db for _all instances_. 
See [this custom alert rule](https://allies-monitoring-alerting.dev.medicmobile.org/alerting/grafana/e5fefa7f-a8aa-4e71-b899-534a3eba8021/view?returnTo=%2Falerting%2Flist) as an example of what things will look like once these changes are applied (spoiler alert, it is not firing for _any_ of the instances tracked on allies-monitoring....)!

fix(#35): fix DB Fragmentation alert on multi-instance deployments

---

.eslintrc
.github/workflows/integration-tests.yml
.gitignore
.npmrc
development/development_patches.js
development/patches/apply/exporters.json.config.scrape_config.yml.patch
development/patches/apply/exporters.postgres.config.scrape_config.yml.patch
development/patches/apply/grafana.provisioning.alerting.cht.yml.patch
development/patches/index.js
development/patches/revert/exporters.json.config.scrape_config.yml.patch
development/patches/revert/exporters.postgres.config.scrape_config.yml.patch
development/patches/revert/grafana.provisioning.alerting.cht.yml.patch
development/tests/integration/alerting/sentinel-backlog.spec.js
development/tests/integration/mocha-hooks.js
development/tests/integration/utils/config.js
development/tests/integration/utils/constants.js
development/tests/integration/utils/docker.js
development/tests/integration/utils/files.js
development/tests/integration/utils/grafana.js
development/tests/integration/utils/index.js
development/tests/integration/utils/prometheus.js
grafana/provisioning/alerting/cht.yml
grafana/provisioning/dashboards/CHT/cht_admin_details.json
grafana/provisioning/dashboards/CHT/cht_admin_overview.json
package-lock.json
package.json

#52 
The goal of these changes is to reduce the noise of the Sentinel Backlog alerts while still consistently alerting when there is a problem that requires action.  
With the new alert logic, we will trigger Sentinel Backlog alerts: _if the backlog is growing at the same rate as changes typically are coming in (`+ 500`). This indicates that basically nothing is getting processed by Sentinel.  (The `500` is just there as a minimum buffer.)_
See the example [Sentinel Backlog (jkuester)](https://allies-monitoring-alerting.dev.medicmobile.org/alerting/grafana/ee276bf5-e7dd-4a6a-bd2e-3d04f8964d2e/view?returnTo=%2Falerting%2Flist) alert rule out on the Allies instance for a live example of the new logic!
Also, if you want to get a historical view of when this alert would have been triggered, …

feat(#52): set dynamic threshold for Sentinel Backlog alert rule

---

exporters/postgres/docker-compose.postgres-exporter.yml

Wrote a bit about this [in the issue](https://github.com/medic/cht-watchdog/issues/55#issuecomment-1587092568) but basically the problem seems to be coming from [this logical replication metrics query](https://github.com/prometheus-community/postgres_exporter/blob/master/collector/replication_slots.go#L53-L59) and disabling the related metrics collector makes the exporter not crash anymore when connected to a Postgres <10 instance.

fix(#55): support postgres <10

---

grafana/provisioning/dashboards/CHT/cht_admin_details.json
grafana/provisioning/dashboards/CHT/cht_admin_overview.json

Closes #63 
Simple change to just add filtering by the `instance` label to the new queries introduced in #58.  This should correct the behavior of the panels on instances recording data for multiple CHT instances.
To test these changes locally, just make sure you have multiple CHT instances configured in your `cht-instances.yml`.  E.g.:
```yaml
- targets:
- http://fake-cht:8081
- https://gamma.dev.medicmobile.org
```
Then, if you spin up the `main` branch you will see multiple gauges displayed on the Overview dashboard for the Sentinel Backlog panel (as noted in the issue).  
Deploy the `52_fix_sentinel_backlog_panesl` branch, and you should see the panel go back to only displaying 1 gauge as expected (and the gauge should update the data is displays when you change the selected CHT …

fix(#63): fix Sentinel Backlog panels for multiple CHT instances

---

development/patches/apply/grafana.provisioning.alerting.cht.yml.patch
development/patches/revert/grafana.provisioning.alerting.cht.yml.patch
development/tests/integration/alerting/outbound-push-backlog.spec.js
development/tests/integration/alerting/sentinel-backlog.spec.js
development/tests/integration/mocha-hooks.js
development/tests/integration/utils/grafana.js
development/tests/integration/utils/index.js
development/tests/integration/utils/prometheus.js
grafana/provisioning/alerting/cht.yml
grafana/provisioning/dashboards/CHT/cht_admin_details.json
grafana/provisioning/dashboards/CHT/cht_admin_overview.json

#52 
Similar to the #58 PR, the goal of these changes is to make the Outbound Backlog alert rule more useful for instances over variable size.
With the new alert logic we will trigger Outbound Push Backlog alerts: _if the backlog is increasing by more than 5% of the the changes rate (with a 5 change minimum buffer). This indicates that a significant percentage of changes are not being properly processed by the outbound push logic._
In addition, I have updated the Outbound Push Backlog panels on both the Overview and Details dashboards to dynamically set the color based on the change rate of the database.
See the [Outbound Push Backlog (jkuester)](https://allies-monitoring-alerting.dev.medicmobile.org/alerting/grafana/d4f818b0-b885-4d16-8089-ddb97cd12a4f/view?returnTo=%2Falerting%2Flist) …

feat(#52): set dynamic threshold for Outbound Push Backlog

---

development/patches/apply/grafana.provisioning.alerting.cht.yml.patch
development/patches/revert/grafana.provisioning.alerting.cht.yml.patch
development/tests/integration/alerting/users-over-replication-limit.spec.js
grafana/provisioning/alerting/cht.yml
grafana/provisioning/dashboards/CHT/cht_admin_details.json
grafana/provisioning/dashboards/CHT/cht_admin_overview.json

#52 
Similar to the #58 and #62 PRs, the goal of these changes is to make the Users Over Replication Limit alert rule more useful for instances over variable size.
With the new alert logic we will trigger Users Over Replication Limit alerts: _if user count is increasing by more than `0.3%` of total users per day (with a 2 user minimum buffer). A meaningful amount of users crossing the replication limit could indicate an issue with recently updated configuration._
In addition, I have updated the Users Over Replication Limit panels on both the Overview and Details dashboards to dynamically set the color based on the user count for the instance.
See the [Users Over Replication Limit (jkuester)](https://allies-monitoring-alerting.dev.medicmobile.org/alerting/grafana/d6284b22-716b-47cb-820e-04d …

feat(#52): set dynamic threshold for Users Over Rep Limit

---

exporters/postgres/config/cht-queries.yml

This PR adds a `where` clause to the couch2pg status query to ensure the columns contain the data the query expects so the `position` calls don't fail when there's bad data
closes #68

fix(#68): defensive couch2pg select

---

exporters/postgres/docker-compose.postgres-exporter.yml

Closes #70
The goal of this PR is to minimize the number of metrics collected from Postgres. This will address 2 problems at the same time! First, the random log errors and other various querying issues when running against crazy old Postgres versions are being triggered when collecting the various default metrics that the postgres_exporter collects about the Postgres instance and its databases.  Turning off these metrics should avoid the errors and quiet the logs.  Secondly, when testing this against the prod Postgres instance, we observed that metric scraping was insanely slow (well above 10sec).  Radically reducing the amount of metrics we are actually collecting from Postgres should help improve the scrape time!
Note that none of the metrics that are being removed were being used in …

fix(#70): disable all non-custom Postgres metrics

---

docker-compose.yml

This PR is needed so users who are extending watchdog can do something like this in an additional YAML compose file:
```yaml
services:
grafana:
volumes:
- ./extra-sql-dashboard.json:/etc/grafana/provisioning/dashboards/CHT/cht_admin_extra_sql.json:ro
```
If not, no extra files can be mounted into `/etc/grafana/provisioning` because [it's read only](https://github.com/medic/cht-watchdog/blob/e12c94bb7d7dcb455b3cb0ab3e7c8ab9cfbf5e44/docker-compose.yml#L43).

feat(compose): make grafana provisioning mount be read/write

---

development/docker-compose.smtp.yml
development/fake-cht/docker-compose.fake-cht.yml
docker-compose.yml
exporters/postgres/docker-compose.postgres-exporter.yml

No dependabot automation included, as [discussed in the issue](https://github.com/medic/cht-watchdog/issues/80#issuecomment-1680958017)

chore(#80): pin docker images versions to the versions currently used

---

grafana/provisioning/dashboards/CHT/cht_partnerships_replication.json

#88 
I noticed this and thought it was an issue with fake-cht and dev stack. Shouldn't have ignored it.  It is now happening on https://allies-monitoring-alerting.dev.medicmobile.org.  
Proposed fix is to refresh the Prometheus datasource ID in the dashboard JSON and that seems to fix it.

fix(#88): refresh prometheus datasource in replication dashboard

---

grafana/provisioning/dashboards/CHT/cht_partnerships_replication.json

#90 
Fixes quit a few bugs in ApDex:
1. Contrains calcs to selected period instead of calculating for all-time
2. ApDex graph should apply to replication routes only
3. One ApDex graph used buckets 90/180 for the thresholds, the other used buckets 180/360. Consolidate on latter.
4. Colour formatting for ApDex < 98 instead of <90
5. Error rate should include ELB timeouts (1 hour)
After changes:

fix(#90): incorrect cht replication dashboard apdex calculations

---

.env.example
.github/dependabot.yml
.github/workflows/conventional-commits.yml
.github/workflows/integration-tests.yml
.github/workflows/release.yml
.husky/commit-msg
docker-compose.yml
exporters/postgres/compose.yml
package-lock.json
package.json

- Prometheus - `v2.46.0` > `v2.54.1`
- Grafana - `10.0.3` > `11.2.0`
There was no major breaking changes to note for the Prometheus upgrade.  For Grafana, I reviewed the [release notes](https://grafana.com/docs/grafana/latest/whatsnew/) and [upgrade guides](https://grafana.com/docs/grafana/latest/upgrade-guide/).  While many things did change, I did not find anything that required a manual migration when updating a Watchdog instance.  All of our default configuration seems compatible with the new version of Grafana.
Following the example of the other docker images, I am pinning the version of `burningalchemist/sql_exporter` (to its latest current release) and I have added the `SQL_EXPORTER_VERSION` envar to the `.env.example` file as the place where users can configure a custom version of …

feat(#112): update default service versions

---

.github/dependabot.yml
.github/workflows/integration-tests.yml

Updating these dependencies is blocked because of the ESM module requirement.
[Dependabot documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#example-disabling-version-updates-for-some-dependencies).
This PR also adds linting to our CI run.  This would have failed the dependabot eslint PR if we were actually running linting.

chore: ignore eslint and chai in dependabot

---

exporters/postgres/cht_sync_collector.yml
exporters/postgres/sql_servers_example.yml
grafana/provisioning/dashboards/CHT/cht_admin_overview.json
index.js

feat: add cht-sync collector and update the sql exporter example

---

README.md

Additionally, [added the missing alias](https://github.com/medic/cht-docs/pull/1684) on the docs site to ensure the old link is not sending `404`s.

chore: update link to docs site

---

prometheus/config/prometheus.yml

this PR adds `scheme: "https"` to the [express metrics scrape config](https://github.com/medic/cht-watchdog/blob/62a7be1e39d9513ed9a174b8d641b3282344a5f5/prometheus/config/prometheus.yml#L12)
see  #128  for some logic around this choice

fix(#128): make express metrics always http

---

grafana/provisioning/dashboards/CHT/cht_partnerships_replication.json

fixes #154
Also taking a moment to update apdex tooltip helptext from:
> Target replication performance under 3min. Tolerated replication performance under 6min.
to instead be:
> The target is a score of 100 means the average user is satisfied (sync under 3 min).  The more users that are tolerating sync (3min to 6min sync) or frustrated (greater than 6min sync), the lower the score is.  See the [Apdex Wikipedia article](https://en.wikipedia.org/wiki/Apdex) for more details.
As shown here:

fix(#154): fix for apdex calculations
